#!/bin/bash
####################################################
# HEADER: This file was autogenerated by puppet.
#
# FILE: modules/koji/files/etc/pki/koji/make_CA.sh
#
# /etc/pki/koji/make_CA.sh file for machine [<%= fqdn %>]
#
#####################################################

BASE=/etc/pki/koji/
BASE_DN='/C=US/ST=STATE/L=CITY/O=EXAMPLE/OU=BUSINESS UNIT'
HOSTNAME=$(hostname --long)
EMAIL_ADDRESS='exampleuser@example.com'

usage() {
    echo "$0 [-h]" >&2
    echo " Basically this sets up a CA" >&2
    echo " for $BASE_DN" >&2
    exit 200
}

args=$(getopt -o h -- "$@")
eval set -- "$args"

for arg in $@; do
    case $1 in
        -h )
            # get help
            usage
           ;;
        -- )
            # end of getopt args, shift off the -- and get out of the loop
            shift
            break 2
           ;;
    esac
done

if [[ ! -w $BASE/ ]] ; then
    echo "Can't write to $BASE" >&2 ; exit 1
fi
if [[ -e $BASE/index.txt ]] ; then
    echo "$BASE/index.txt exists" >&2 ; exit 1
fi
if [[ -e $BASE/serial ]] ; then
    echo "$BASE/serial exists" >&2 ; exit 1
fi
if [[ -e $BASE/ca_cert.crt ]] ; then
    echo "$BASE/ca_cert.crt exists" >&2 ; exit 1
fi
if [[ -e $BASE/private/ca_cert.key ]] ; then
    echo "$BASE/private/ca_cert.key exists" >&2 ; exit 1
fi


touch $BASE/index.txt
echo 01 > $BASE/serial

mkdir -p $BASE/certs
mkdir -p $BASE/csrs
mkdir -p $BASE/private
chmod 751 $BASE/private

# make key
openssl genrsa -out $BASE/private/ca_cert.key 2048
if [[ $? -ne 0 ]]; then
   exit 1
fi

# make CA cert
openssl req -config $BASE/openssl.cnf -new -utf8 -x509 -days 12950 -subj "$BASE_DN/CN=$HOSTNAME/emailAddress=$EMAIL_ADDRESS" -extensions v3_ca -key $BASE/private/ca_cert.key -out $BASE/ca_cert.crt
if [[ $? -ne 0 ]]; then
   exit 1
fi

# setup for the system TLS/Cert list
ln -f $BASE/ca_cert.crt /etc/pki/tls/certs/koji_ca_cert.crt
if [[ $? -ne 0 ]]; then
   exit 1
fi
