#!/bin/bash
####################################################
# HEADER: This file was autogenerated by puppet.
#
# FILE: modules/koji/files/etc/pki/koji/make_default_koji_certs.sh
#
# /etc/pki/koji/make_default_koji_certs.sh file for machine [<%= fqdn %>]
#
#####################################################

BASE=/etc/pki/koji/
HOSTNAME=$(hostname --long)

usage() {
    echo "$0 [-h]" >&2
    echo " Basically this sets up a CA" >&2
    echo " for koji along with a number of default certs" >&2
    exit 200
}

args=$(getopt -o h -- "$@")
eval set -- "$args"

for arg in $@; do
    case $1 in
        -h )
            # get help
            usage
           ;;
        -- )
            # end of getopt args, shift off the -- and get out of the loop
            shift
            break 2
           ;;
    esac
done

cd $BASE

$BASE/make_CA.sh
if [[ $? -ne 0 ]]; then
   exit 1
fi

###########################################################
# Make host key
$BASE/make_koji_service_cert.sh -c $HOSTNAME
if [[ $? -ne 0 ]]; then
    exit 1
fi
# make kojid happy
mkdir -p /etc/kojid/
if [[ ! -e /etc/kojid/${HOSTNAME}.pem ]]; then
    ln -s $BASE/pems/${HOSTNAME}.pem /etc/kojid/
    if [[ $? -ne 0 ]]; then
        exit 1
    fi
fi

###########################################################
# make koji-web service key
$BASE/make_koji_service_cert.sh -c $HOSTNAME -o koji-web
if [[ $? -ne 0 ]]; then
    exit 1
fi
# make apache happy
if [[ ! -e /etc/pki/tls/certs/localhost.crt ]]; then
    ln -s $BASE/certs/${HOSTNAME}_koji-web.crt  /etc/pki/tls/certs/localhost.crt
    if [[ $? -ne 0 ]]; then
        exit 1
    fi
fi
if [[ ! -e /etc/pki/tls/private/localhost.key ]]; then
    ln -s $BASE/private/${HOSTNAME}_koji-web.key  /etc/pki/tls/private/localhost.key
    if [[ $? -ne 0 ]]; then
        exit 1
    fi
fi
# make koji-web happy
mkdir -p /etc/kojiweb/
if [[ ! -e /etc/kojiweb/${HOSTNAME}_koji-web.pem ]]; then
    ln -s $BASE/pems/${HOSTNAME}_koji-web.pem /etc/kojiweb/
    if [[ $? -ne 0 ]]; then
        exit 1
    fi
fi

###########################################################
# make kojira service key
$BASE/make_koji_service_cert.sh -c kojira
if [[ $? -ne 0 ]]; then
    exit 1
fi
# make kojira happy
mkdir -p /etc/kojira/
if [[ ! -e /etc/kojira/kojira.pem ]]; then
    ln -s $BASE/pems/kojira.pem /etc/kojira/
    if [[ $? -ne 0 ]]; then
        exit 1
    fi
fi

###########################################################
# make koji-admin user key
$BASE/make_koji_service_cert.sh -c koji-admin
if [[ $? -ne 0 ]]; then
    exit 1
fi
